version: '3.5'
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    hostname: 'nextcloud-postgres'
    volumes:
      - ./db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing123
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    expose:
      - 80
      - 9000
    volumes:
      - app_data:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud-postgres
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing123
    depends_on:
      - db

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
volumes:
  document_data:
  document_log:
  app_data:
  db:
